### ISSUE TITLE
Initialize save dir with cloud content (for new installation)

### ISSUE THREAD

**Issue by hicwic** [DavidDeSimone/OpenCloudSaves#93] opened 2023-03-23 13:49 UTC
i'm struggling initalizing my save sync between my pc and my deck.
use case:
- i have elden ring on my pc with an already existing save game
- this savedgame is synched with open cloud saves on my google drive (the files are here)
- installed the game on my deck, created prefixes, etc...
- for now my savegame directory is empty on my deck, and i want open cloud saves to download the existing save synched on my google drive.

problem: 
- as the savegame dir is empty on my deck, the sync button is greyed
- if i manualy create the directory the button is no more greyed, but *i think* as the directory is newer as my already synched one, nothing is done

proposition:
add a button or a checkbox "force download" to intialize the save game dir with content on cloud (as we can see on heroic for example)

maybe we can achieve the same with addititonnal rclone parameters, but as i'm new to this tool, and the man page is huuuuuuge, i d'ont know which parameter to use :)

**Comment by hicwic** [comment] 2023-03-23 15:51
i'll give you the screen later, i'm at work right now

i manualy created the steamID folder, but the .sl2 file was not here, since i never launched the game on my deck
so if i include *.sl2, the sync button is greyed as there is no file detected.

with you idea to create a dummy file, if i create a dummy ER0000.sl2 on my deck, will it erase the one on the cloud as it will be newer ? what's the update policy of the cloud part ?

**Comment by DavidDeSimone** [comment] 2023-03-23 16:07
> i'll give you the screen later, i'm at work right now
> 
> i manualy created the steamID folder, but the .sl2 file was not here, since i never launched the game on my deck so if i include *.sl2, the sync button is greyed as there is no file detected.
> 
> with you idea to create a dummy file, if i create a dummy ER0000.sl2 on my deck, will it erase the one on the cloud as it will be newer ? what's the update policy of the cloud part ?

Understood, take your time.

I would recommend calling the dummy file something like "dummy.txt". It would just be there to to un-gray out that button.

The update policy is that is uses the latest timestamp for the same file (based on name). Unless you use bisync (default to off), our sync process won't delete files.

**Comment by DavidDeSimone** [comment] 2023-03-23 16:54
> Ok, got it
> 
> I can't figure what bisync do in comparison of normal sync. And what's the use case. Maybe it's me 😼

Not on you - I need to add a better explanation in app.

Basically our standard sync won't delete files on the cloud if you delete them locally, bisync will. The issue is that bisync needs both clients to be in sync with the cloud - it's not for "merging" sets of save states. I found it was very common for users to have two different sets of saves on their devices, and when they started using Open Cloud Save, they wanted to "combine" their save sets, which won't work with bisync.

The downside is that without bisync, you can't delete files.

**Comment by DavidDeSimone** [comment] 2023-04-04 04:17
Going to close this as it should be fixed by 0.18.1 - let me know if you still have issues in this use case.

**Closed by DavidDeSimone** 2023-04-04 04:17 UTC
Labels: enhancement

**Comment by hicwic** [comment] 2023-04-14 08:32
could you push the 0.18.1 on flatpack ? don't see it on my SD :s

**Comment by DavidDeSimone** [comment] 2023-04-14 16:13
> could you push the 0.18.1 on flatpack ? don't see it on my SD :s

So I forgot to bump the version number in the manifest, but what is currently on the store as 0.18.0 should be 0.18.1 - I am going to re-release that version as 0.18.1 just to avoid confusion.
